theme: minima
title: Javon-G Live Portfolio
description: Comprehensive outlook on my skills, projects, and goals
author: Javon Garcia
  
plugins:
  - jekyll-feed

feed:
  disable: true
  
header_pages:
  - index.md
  - about.md
  - projects.md
